# app_secrets.py
DATABASE_PASSWORD = "N6BnA4O5nmvEATsl"
GCLOUD_PROJECT = "athletics-hub"
OPENAI_API_KEY = "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"
DATABASE_USERNAME = "colinfitzgerald"
DATABASE_NAME = "track_athletes"
COLLECTION_NAME = "athlete_profile_data"
LETSRUN_COLLECTION_NAME = "letsrun_summaries"
COHERE_API_KEY = "wdlGUm5xd4xK4xP4HCEcJ4Ow68atOAdUr37ABR6Y"
DEEPINFRA_API_KEY = "c5SNCP1x4rEZq6b3OlMw9d9LjaHy3qIh"
INSTAGRAM_USERNAME = "chasefeldspar"
INSTAGRAM_PASSWORD = "iriquois23!"
PINECONE_API_KEY = "33475028-f7ba-402b-bf0e-442e0524dfdc"
PINECONE_ENV = "gcp-starter"
PINECONE_INDEX_NAME = "semantic-search-cohere"
